In [2]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv(r"C:\Users\vchan\OneDrive\Desktop\mumbai_local\data\raw\Mumbai Local Train Dataset.csv",encoding="latin1")
df

,Station,Station Code,Line,Distance From Previous of the Line,Time taken From Previous of the Line,About,Platforms,Tracks,Year of Opening,Nearby attractions,Number of Passengers,Previous names
0,Churchgate,CCG,Western,0 KM,0 min,The Fort area built by the British had three m...,4.0,4.0,1867.0,"Marine Drive,Nariman Point,Flora Fountain",NaN,NaN
1,Marine Lines,MEL,Western,1 KM,3 min,Marine Lines (station code: MEL) is a railway ...,4.0,4.0,1867.0,"Marine Drive,Girgaum Chowpatty Beach,Taraporew...",NaN,NaN
2,Charni Road,CYR,Western,1 KM,2 min,"Charni Road (formerly Churney Road, station co...",4.0,4.0,1867.0,"Girgaum Chowpatty Beach,Taraporewala Aquarium,...",NaN,NaN
3,Grant Road,GTR,Western,1 KM,3 min,"Grant Road (/gra?nt/; station code: GTR), form...",4.0,4.0,NaN,"Taraporewala Aquarium,Girgaum Chowpatty Beach,...",NaN,NaN
4,Mumbai Central,MMCT,Western,1 KM,2 min,"Mumbai Central (formerly Bombay Central, stati...",9.0,9.0,1930.0,"Haji Ali Dargah,Mahalakshmi Temple,Nehru Plane...",NaN,Bellasis Road (Suburban station) Bombay Centra...
...,...,...,...,...,...,...,...,...,...,...,...,...
197,Neral,NRL,Neral-Matheran,0 KM,0 min,Neral Junction is a railway station on the Cen...,2.0,2.0,NaN,"Matheran Hill Railway,Louisa Point,Charlotte Lake",NaN,NaN
198,Jumapatti,JTT,Neral-Matheran,5 KM,46 min,Jummapatti railway station is a railway statio...,NaN,NaN,NaN,"Manas Mandir,Tungareshwar Wildlife Sanctuary,M...",NaN,NaN
199,Waterpipe,WTP,Neral-Matheran,6 KM,46 min,Water Pipe railway station is a railway statio...,NaN,NaN,NaN,"Manas Mandir,Tungareshwar Wildlife Sanctuary,M...",NaN,NaN
200,Aman Lodge,AMNA,Neral-Matheran,7 KM,50 min,Aman Lodge railway station is a railway statio...,NaN,NaN,NaN,"Louisa Point,Echo Point,Panorama Point",NaN,NaN
201,Matheran,MAE,Neral-Matheran,2 KM,18 min,Matheran Railway Station is the upper terminus...,NaN,NaN,1907.0,"Charlotte Lake,Louisa Point,Panorama Point",NaN,NaN

### Basic Formalitites

In [6]:
print(df.shape)

(202, 12)

In [7]:
print(df.columns.tolist())

['Station', 'Station Code', 'Line', 'Distance From Previous of the Line', 'Time taken From Previous of the Line', 'About', 'Platforms', 'Tracks', 'Year of Opening ', 'Nearby attractions', 'Number of Passengers ', 'Previous names']

In [8]:
print(df.isnull().sum())

Station                                   0
Station Code                              0
Line                                      0
Distance From Previous of the Line        0
Time taken From Previous of the Line      0
About                                     0
Platforms                                 5
Tracks                                    9
Year of Opening                         119
Nearby attractions                        0
Number of Passengers                    181
Previous names                          191
dtype: int64

### Dropping Unncessary things and syntactic changes

In [9]:
df = df.drop(columns=['About', 'Number of Passengers ', 'Previous names'])
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

### Better Visualizing Data

In [10]:
df['distance_km'] = df['distance_from_previous_of_the_line'].str.replace(' KM', '').str.strip()
df['travel_time_min'] = df['time_taken_from_previous_of_the_line'].str.replace(' min', '').str.strip()

In [11]:
df = df.drop(columns=['distance_from_previous_of_the_line', 'time_taken_from_previous_of_the_line'])

### Dtype Conversion

In [12]:
df['distance_km'] = pd.to_numeric(df['distance_km'], errors='coerce')
df['travel_time_min'] = pd.to_numeric(df['travel_time_min'], errors='coerce')

In [13]:
df

,station,station_code,line,platforms,tracks,year_of_opening,nearby_attractions,distance_km,travel_time_min
0,Churchgate,CCG,Western,4.0,4.0,1867.0,"Marine Drive,Nariman Point,Flora Fountain",0,0
1,Marine Lines,MEL,Western,4.0,4.0,1867.0,"Marine Drive,Girgaum Chowpatty Beach,Taraporew...",1,3
2,Charni Road,CYR,Western,4.0,4.0,1867.0,"Girgaum Chowpatty Beach,Taraporewala Aquarium,...",1,2
3,Grant Road,GTR,Western,4.0,4.0,NaN,"Taraporewala Aquarium,Girgaum Chowpatty Beach,...",1,3
4,Mumbai Central,MMCT,Western,9.0,9.0,1930.0,"Haji Ali Dargah,Mahalakshmi Temple,Nehru Plane...",1,2
...,...,...,...,...,...,...,...,...,...
197,Neral,NRL,Neral-Matheran,2.0,2.0,NaN,"Matheran Hill Railway,Louisa Point,Charlotte Lake",0,0
198,Jumapatti,JTT,Neral-Matheran,NaN,NaN,NaN,"Manas Mandir,Tungareshwar Wildlife Sanctuary,M...",5,46
199,Waterpipe,WTP,Neral-Matheran,NaN,NaN,NaN,"Manas Mandir,Tungareshwar Wildlife Sanctuary,M...",6,46
200,Aman Lodge,AMNA,Neral-Matheran,NaN,NaN,NaN,"Louisa Point,Echo Point,Panorama Point",7,50
201,Matheran,MAE,Neral-Matheran,NaN,NaN,1907.0,"Charlotte Lake,Louisa Point,Panorama Point",2,18

### Checking Different types of lines

In [16]:
df['line'].value_counts()

line
Central 1              40
Western                37
Central 2              37
Harbour                25
Dahanu-Virar-Panvel    22
Diva-Roha              17
Trans Harbour          14
Uran                    5
Neral-Matheran          5
Name: count, dtype: int64

## The project is based on 3 Main lines ie Central,harbour,western not the outskirts

In [18]:
main_lines = ['Western', 'Central 1', 'Central 2', 'Harbour']
df = df[df['line'].isin(main_lines)]

In [22]:
df.shape

(139, 9)

In [21]:
df['line'].value_counts()

line
Central 1    40
Western      37
Central 2    37
Harbour      25
Name: count, dtype: int64

In [23]:
df.to_csv(r"C:\Users\vchan\OneDrive\Desktop\mumbai_local\data\processed\stations_clean.csv", index=False)
print("Saved!")

Saved!